### ISSUE TITLE
请问怎么取消点击视频时的暂停事件

### ISSUE THREAD

**Issue by guyijie1211** [zhw2590582/ArtPlayer#145]
就是只通过播放暂停按钮来控制播放和暂停。点击视频内容的时候不触发

**Comment by zhw2590582** [comment]
加个样式就可以了
```css
.art-video {
   pointer-events: none;
}
```
