### ISSUE TITLE
How disable Video info?

### ISSUE THREAD

**Issue by hippomu-media** [zhw2590582/ArtPlayer#150]
How disable video info?
![Screenshot_2021-07-20-05-49-05-80](https://user-images.githubusercontent.com/74494691/126237349-643e7ab8-5a9c-4bce-8e7f-a742b17f8058.png)

**Comment by zhw2590582** [comment]
```css
.art-contextmenu-info {
  display: none;
}
```
