### ISSUE TITLE
Subtitle switch scroll

### ISSUE THREAD

**Issue by hippomu-media** [zhw2590582/ArtPlayer#161]
![Screenshot_2021-09-05-15-01-42-66](https://user-images.githubusercontent.com/74494691/132119935-3643ace3-5e64-4f4e-b028-32fb99ba0c55.png)

**Comment by hippomu-media** [comment]
![Screenshot_2021-09-05-15-09-01-74](https://user-images.githubusercontent.com/74494691/132120117-24fd553d-4ba3-4d47-92e7-ed048d246396.png)

**Comment by zhw2590582** [comment]
You just need to add the following styles
```css
.art-selector-list {
    max-height: 100px;
    overflow: auto;
}
```
