### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by ahmedalashhab** [zhw2590582/ArtPlayer#413]
Hi!
Thank you for your beautiful video player. It is by far the easiest and best video player I've ever worked with.
I'd like to know, how can I style the thickness of the seeker bar? 

<img width="819" alt="image" src="https://user-images.githubusercontent.com/96653465/199717279-3723121d-e73e-4d85-8f84-c31545c4ce97.png">

**Comment by zhw2590582** [comment]
```css
.art-control-progress {
    height: 5px !important;
}
```
