### ISSUE TITLE
ArtPlayer Setting full style fills the screen

### ISSUE THREAD

**Issue by flixmu** [zhw2590582/ArtPlayer#453]
![Screenshot_2023-01-20-13-47-11-79](https://user-images.githubusercontent.com/84267010/213634743-f33bae59-1078-4b8f-9f6f-4c6bcad4cc1c.png)
Like this

**Comment by zhw2590582** [comment]
Try this:

```css
.art-mobile .art-settings {
    left: 0 !important;
    top: 0 !important;
    right: 0 !important;
    width: 100% !important;
}
```
