### ISSUE TITLE
Add a background opacity in the subtitles

### ISSUE THREAD

**Issue by x3inspire** [zhw2590582/ArtPlayer#612]
Hi,

Can add a background opacity in the subtitles setting? It can help with seeing the subtitles more clearly without using too much focus.

**Comment by zhw2590582** [comment]
You can add additional styles：

```css
.art-subtitle p {
  background: rgb(0 0 0 / 50%);
}
```
