### ISSUE TITLE
我想禁止滑动或者拖拽进度条请问需要怎么操作

### ISSUE THREAD

**Issue by ty536804** [zhw2590582/ArtPlayer#715]
我想禁止滑动或者拖拽进度条请问需要怎么操作，是否有相关的属性。

**Comment by zhw2590582** [comment]
可以添加css

```css
.art-progress {
    pointer-events: none;
}
```
